(function() {var implementors = {};
implementors["embedded_hal"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"embedded_hal/spi/struct.Mode.html\" title=\"struct embedded_hal::spi::Mode\">Mode</a>",synthetic:true,types:["embedded_hal::spi::Mode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"embedded_hal/spi/enum.Polarity.html\" title=\"enum embedded_hal::spi::Polarity\">Polarity</a>",synthetic:true,types:["embedded_hal::spi::Polarity"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"embedded_hal/spi/enum.Phase.html\" title=\"enum embedded_hal::spi::Phase\">Phase</a>",synthetic:true,types:["embedded_hal::spi::Phase"]},];
implementors["nb"] = [{text:"impl&lt;E&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"nb/enum.Error.html\" title=\"enum nb::Error\">Error</a>&lt;E&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;E: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["nb::Error"]},];
implementors["ssd1306"] = [{text:"impl&lt;I2C&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"ssd1306/struct.Ssd1306.html\" title=\"struct ssd1306::Ssd1306\">Ssd1306</a>&lt;I2C&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;I2C: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["ssd1306::Ssd1306"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.Command.html\" title=\"enum ssd1306::cmd::Command\">Command</a>",synthetic:true,types:["ssd1306::cmd::Command"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.HScrollDir.html\" title=\"enum ssd1306::cmd::HScrollDir\">HScrollDir</a>",synthetic:true,types:["ssd1306::cmd::HScrollDir"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.VHScrollDir.html\" title=\"enum ssd1306::cmd::VHScrollDir\">VHScrollDir</a>",synthetic:true,types:["ssd1306::cmd::VHScrollDir"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.Page.html\" title=\"enum ssd1306::cmd::Page\">Page</a>",synthetic:true,types:["ssd1306::cmd::Page"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.NFrames.html\" title=\"enum ssd1306::cmd::NFrames\">NFrames</a>",synthetic:true,types:["ssd1306::cmd::NFrames"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.AddrMode.html\" title=\"enum ssd1306::cmd::AddrMode\">AddrMode</a>",synthetic:true,types:["ssd1306::cmd::AddrMode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.VcomhLevel.html\" title=\"enum ssd1306::cmd::VcomhLevel\">VcomhLevel</a>",synthetic:true,types:["ssd1306::cmd::VcomhLevel"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
