(function() {var implementors = {};
implementors["nb"] = [{text:"impl&lt;E&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"nb/enum.Error.html\" title=\"enum nb::Error\">Error</a>&lt;E&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;E: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>,&nbsp;</span>",synthetic:false,types:["nb::Error"]},];
implementors["ssd1306"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.Command.html\" title=\"enum ssd1306::cmd::Command\">Command</a>",synthetic:false,types:["ssd1306::cmd::Command"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.HScrollDir.html\" title=\"enum ssd1306::cmd::HScrollDir\">HScrollDir</a>",synthetic:false,types:["ssd1306::cmd::HScrollDir"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.VHScrollDir.html\" title=\"enum ssd1306::cmd::VHScrollDir\">VHScrollDir</a>",synthetic:false,types:["ssd1306::cmd::VHScrollDir"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.Page.html\" title=\"enum ssd1306::cmd::Page\">Page</a>",synthetic:false,types:["ssd1306::cmd::Page"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.NFrames.html\" title=\"enum ssd1306::cmd::NFrames\">NFrames</a>",synthetic:false,types:["ssd1306::cmd::NFrames"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.AddrMode.html\" title=\"enum ssd1306::cmd::AddrMode\">AddrMode</a>",synthetic:false,types:["ssd1306::cmd::AddrMode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"ssd1306/cmd/enum.VcomhLevel.html\" title=\"enum ssd1306::cmd::VcomhLevel\">VcomhLevel</a>",synthetic:false,types:["ssd1306::cmd::VcomhLevel"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
